### ISSUE TITLE
[EPIC, MVP] Game Prototype

### ISSUE THREAD

**Issue by miking-the-viking** [miking-the-viking/game-of-git#33]
- Plan
    - [ ] Game Flow,
    - [ ] Goals and Objectives,
    - [ ] Initial Genre (more can be added later)
    - [ ] Initial Art Styles (Vic's help, ideally)
    - [ ] Game Engine
- Develop & Tests
- Alpha & Beta Tests (?)
- ...

**Comment by miking-the-viking** [comment]
# Game Engine

https://colorlib.com/wp/javascript-engines-for-building-games/

- Phaser
- Pixi.js
- Unity (Web Assembly v. WebGL)
