### ISSUE TITLE
CD Pipeline

### ISSUE THREAD

**Issue by miking-the-viking** [miking-the-viking/game-of-git#5]
To be investigated and broken down.

- [ ] Deployment Story
  - [ ] Hosting and Cost analysis
  - [ ] Pulumi Setup
  - [ ] Secure Credential Storage
  - [ ] Git Strategy (Branch/Tag/Etc.)
