### ISSUE TITLE
NestJs Unit Tests & Stability

### ISSUE THREAD

**Issue by miking-the-viking** [miking-the-viking/game-of-git#64]
Fix and flesh out all the NestJs Tests. Use as TDD opportunity to improve stability and edge cases

- [x] All tests are in a neutral "passing" state (not failing, ready for development/review)
- [ ] All unit tests have been developed
- [ ] Reorganized between internal representations of git entity models and external representations of git entity models, such as GitHub's
  - ex: `/repositories` vs. `/git/repositories` compared to `/user.internal` vs `/user.github`

- [ ] Entities
  - [x] App
  - [x] App Event
  - [x] Auth
  - [ ] Game
  - [ ] Git
    - [ ] Branch
    - [ ] Client
      - [ ] App Key
      - [ ] Webhooks
    - [ ] Comment
    - [ ] Commit
    - [ ] File Diff
    - [ ] Issue
    - [ ] Label
    - [ ] Pull Request
    - [ ] Pull Request Review
    - [ ] Repository
    - [ ] Review Request
    - [ ] Review Thread
    - [ ] Topic
    - [ ] User
  - [ ] Repositories
  - [x] User
