### ISSUE TITLE
Containerized Test Env with Real Prisma and DBs

### ISSUE THREAD

**Issue by miking-the-viking** [miking-the-viking/game-of-git#67]
In order to maximize the efficacy of the tests it is best to try to be as E2E as possible, for this reason it would be invaluable to setup a parallel test environment that can be invoked as needed and allows jest tests to actually interact with these databases/services instead of mocking this functionality.

- [ ] New docker-compose that spins up 
  - [ ] Prisma
  - [ ] DynamoDB-local
  - [ ] PostgresSQL
- [ ] New ENVs to reflect these new services
- [ ] NestJS App modifications to use test configurations when testing vs. base configs
  - [ ] Prisma Endpoint
  - [ ] Prisma Port
  - [ ] DB Host
  - [ ] DB Credentials
