### ISSUE TITLE
REAL GitHub Service & Webhook Testing

### ISSUE THREAD

**Issue by miking-the-viking** [miking-the-viking/game-of-git#68]
Setup configuration and POC for setting up a demonstration repository and testing the full E2E for various webhook event types and their implications on the rest of the system.

- [ ] ENV Modifications
  - [ ] GitHub Testing AppKey
  - [ ] GitHub Testing Repository Name
  - [ ] GitHub Testing User Name
  - [ ] NestJs Public URL
   - [ ] CI Strategy for Public URL exposure...
- [ ] Setup/Teardown Strategy
