### ISSUE TITLE
React App Migration

### ISSUE THREAD

**Issue by miking-the-viking** [miking-the-viking/game-of-git#74]
# Complete Migration to React

## Todo

- [x] Route Manager
  - [x] Meta implemented for existing routes
  - [x] Used in Navbar item generation/groupings
- [x] NavBar
  - [x] Styling
  - [x] Item Nesting
- [x] System Toast w/ toast queue (for global notifications, messages, etc.)
- [ ] Create Game
- [ ] Game
  - [ ] Repository Overview Data
  - [ ] Webhook Stream
- [ ] Dashboard
- [ ] Settings
  - [ ] Dark Mode
- [ ] Remaining front end code tested
- [ ] Webhook Events Websocket
- [ ] Notifications Websocket
  - [ ] App Event toast

## Last

- [ ] Ensure it's all tested, asshole.
- [ ] Delete the old Vue web-app
